AcmeUserBundle:
    resource: "@AcmeUserBundle/Controller/"
    type:     annotation
    prefix:   /


AcmeSecurityBundle:
    resource: "@AcmeSecurityBundle/Resources/config/routing.yml"
    prefix:   /

OSPTTestBundle:
    resource: "@OSPTTestBundle/Resources/config/routing.yml"
    prefix:   /test

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
