parameters:
#    ospt_test.example.class: OSPT\TestBundle\Example

services:
#    ospt_test.example:
#        class: %ospt_test.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
